# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p
from .MoneroKeyImageExportInit import MoneroKeyImageExportInit
from .MoneroKeyImageSyncFinal import MoneroKeyImageSyncFinal
from .MoneroKeyImageSyncStep import MoneroKeyImageSyncStep


class MoneroKeyImageSync(p.MessageType):
    MESSAGE_WIRE_TYPE = 511
    FIELDS = {
        1: ('init', MoneroKeyImageExportInit, 0),
        2: ('step', MoneroKeyImageSyncStep, 0),
        3: ('final_msg', MoneroKeyImageSyncFinal, 0),
    }

    def __init__(
        self,
        init: MoneroKeyImageExportInit = None,
        step: MoneroKeyImageSyncStep = None,
        final_msg: MoneroKeyImageSyncFinal = None,
    ) -> None:
        self.init = init
        self.step = step
        self.final_msg = final_msg
