# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p
from .MoneroTransactionAllOutSet import MoneroTransactionAllOutSet
from .MoneroTransactionFinal import MoneroTransactionFinal
from .MoneroTransactionInit import MoneroTransactionInit
from .MoneroTransactionInputVini import MoneroTransactionInputVini
from .MoneroTransactionInputsPermutation import MoneroTransactionInputsPermutation
from .MoneroTransactionMlsagDone import MoneroTransactionMlsagDone
from .MoneroTransactionSetInput import MoneroTransactionSetInput
from .MoneroTransactionSetOutput import MoneroTransactionSetOutput
from .MoneroTransactionSignInput import MoneroTransactionSignInput


class MoneroTransactionSign(p.MessageType):
    FIELDS = {
        1: ('init', MoneroTransactionInit, 0),
        2: ('set_input', MoneroTransactionSetInput, 0),
        3: ('input_permutation', MoneroTransactionInputsPermutation, 0),
        4: ('input_vini', MoneroTransactionInputVini, 0),
        5: ('set_output', MoneroTransactionSetOutput, 0),
        6: ('all_out_set', MoneroTransactionAllOutSet, 0),
        7: ('mlsag_done', MoneroTransactionMlsagDone, 0),
        8: ('sign_input', MoneroTransactionSignInput, 0),
        9: ('final_msg', MoneroTransactionFinal, 0),
    }

    def __init__(
        self,
        init: MoneroTransactionInit = None,
        set_input: MoneroTransactionSetInput = None,
        input_permutation: MoneroTransactionInputsPermutation = None,
        input_vini: MoneroTransactionInputVini = None,
        set_output: MoneroTransactionSetOutput = None,
        all_out_set: MoneroTransactionAllOutSet = None,
        mlsag_done: MoneroTransactionMlsagDone = None,
        sign_input: MoneroTransactionSignInput = None,
        final_msg: MoneroTransactionFinal = None,
    ) -> None:
        self.init = init
        self.set_input = set_input
        self.input_permutation = input_permutation
        self.input_vini = input_vini
        self.set_output = set_output
        self.all_out_set = all_out_set
        self.mlsag_done = mlsag_done
        self.sign_input = sign_input
        self.final_msg = final_msg
