# Automatically generated by pb2py
from .. import protobuf as p


class MoneroTsxSignInputResp(p.MessageType):
    MESSAGE_WIRE_TYPE = 309
    FIELDS = {
        1: ('signature', p.BytesType, 0),
        2: ('cout', p.BytesType, 0),
    }

    def __init__(
        self,
        signature: bytes = None,
        cout: bytes = None
    ) -> None:
        self.signature = signature
        self.cout = cout
