# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p


class MoneroLiteRequest(p.MessageType):
    MESSAGE_WIRE_TYPE = 542
    FIELDS = {
        1: ('ins', p.UVarintType, 0),
        2: ('p1', p.UVarintType, 0),
        3: ('p2', p.UVarintType, 0),
        4: ('data', p.BytesType, 0),
    }

    def __init__(
        self,
        ins: int = None,
        p1: int = None,
        p2: int = None,
        data: bytes = None,
    ) -> None:
        self.ins = ins
        self.p1 = p1
        self.p2 = p2
        self.data = data
