# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p


class MoneroRespError(p.MessageType):
    MESSAGE_WIRE_TYPE = 500
    FIELDS = {
        1: ('status', p.UVarintType, 0),
        2: ('reason', p.UnicodeType, 0),
        3: ('exc', p.UnicodeType, 0),
    }

    def __init__(
        self,
        status: int = None,
        reason: str = None,
        exc: str = None,
    ) -> None:
        self.status = status
        self.reason = reason
        self.exc = exc
