# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p


class MoneroLiteAck(p.MessageType):
    MESSAGE_WIRE_TYPE = 543
    FIELDS = {
        1: ('sw', p.UVarintType, 0),
        2: ('data', p.BytesType, 0),
    }

    def __init__(
        self,
        sw: int = None,
        data: bytes = None,
    ) -> None:
        self.sw = sw
        self.data = data
