# Automatically generated by pb2py
from .. import protobuf as p


class MoneroTsxAllOutSetResp(p.MessageType):
    MESSAGE_WIRE_TYPE = 307
    FIELDS = {
        1: ('extra', p.BytesType, 0),
        2: ('tx_prefix_hash', p.BytesType, 0),
        3: ('rv', p.BytesType, 0),
    }

    def __init__(
        self,
        extra: bytes = None,
        tx_prefix_hash: bytes = None,
        rv: bytes = None
    ) -> None:
        self.extra = extra
        self.tx_prefix_hash = tx_prefix_hash
        self.rv = rv
