# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p


class MoneroAddress(p.MessageType):
    MESSAGE_WIRE_TYPE = 531
    FIELDS = {
        1: ('address', p.BytesType, 0),
    }

    def __init__(
        self,
        address: bytes = None,
    ) -> None:
        self.address = address
