# Automatically generated by pb2py
from .. import protobuf as p


class MoneroKey(p.MessageType):
    MESSAGE_WIRE_TYPE = 335
    FIELDS = {
        1: ('watch_key', p.BytesType, 0),
        2: ('spend_key', p.BytesType, 0),
        3: ('address', p.BytesType, 0),
    }

    def __init__(
        self,
        watch_key: bytes = None,
        spend_key: bytes = None,
        address: bytes = None
    ) -> None:
        self.watch_key = watch_key
        self.spend_key = spend_key
        self.address = address
