# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p


class MoneroTransactionSignInputAck(p.MessageType):
    FIELDS = {
        1: ('signature', p.BytesType, 0),
        2: ('cout', p.BytesType, 0),
    }

    def __init__(
        self,
        signature: bytes = None,
        cout: bytes = None,
    ) -> None:
        self.signature = signature
        self.cout = cout
