# Automatically generated by pb2py
from .. import protobuf as p


class MoneroAddress(p.MessageType):
    MESSAGE_WIRE_TYPE = 331
    FIELDS = {
        1: ('address', p.BytesType, 0),
    }

    def __init__(
        self,
        address: bytes = None
    ) -> None:
        self.address = address
