# Automatically generated by pb2py
from .. import protobuf as p
if __debug__:
    try:
        from typing import List
    except ImportError:
        List = None


class MoneroTsxInputsPermutation(p.MessageType):
    FIELDS = {
        1: ('perm', p.UVarintType, p.FLAG_REPEATED),
    }

    def __init__(
        self,
        perm: List[int] = None
    ) -> None:
        self.perm = perm if perm is not None else []
