# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p


class TezosDelegationType(p.MessageType):
    FIELDS = {
        1: ('delegate', p.BytesType, 0),
    }

    def __init__(
        self,
        delegate: bytes = None,
    ) -> None:
        self.delegate = delegate
