# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p


class TronWitnessCreateContract(p.MessageType):
    FIELDS = {
        1: ('url', p.UnicodeType, 0),
    }

    def __init__(
        self,
        url: str = None,
    ) -> None:
        self.url = url
