# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p


class TronUpdateAssetContract(p.MessageType):
    FIELDS = {
        1: ('description', p.UnicodeType, 0),
        2: ('url', p.UnicodeType, 0),
    }

    def __init__(
        self,
        description: str = None,
        url: str = None,
    ) -> None:
        self.description = description
        self.url = url
